# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-api
  title: サンプルAPI
  description: デモンストレーション用のAPIです（実際には存在しません）
  tags:
    - rest
    - test
spec:
  type: openapi
  lifecycle: experimental
  owner: user:default/user
  lifecycle: production
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: Sample API
        version: 1.0.0
      paths:
        /hello:
          get:
            summary: Hello World
            responses:
              '200':
                description: OK
