apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-api
  description: Minimal API test
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: Hello API
        version: 1.0.0
      paths:
        /hello:
          get:
            summary: Greet
            responses:
              '200':
                description: OK
