# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-api
  description: Simple sample API
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: Sample API
        version: 1.0.0
      paths:
        /hello:
          get:
            summary: Returns a greeting message
            responses:
              '200':
                description: successful response
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        message:
                          type: string
                          example: "Hello, world!"
